In [1]:
import pandas as pd

In [2]:
sysbo_df = pd.read_csv('../scraper/src/data/sysbo.csv')
ratebeer_df = pd.read_csv('../scraper/src/data/ratebeer.csv')
beeradv_df = pd.read_csv('../scraper/src/data/beeradvocate.csv')

In [3]:
sysbo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19522 entries, 0 to 19521
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   number           19522 non-null  int64
 1   name             19522 non-null  object
 2   abv              19522 non-null  float64
 3   price            19522 non-null  float64
 4   volume_ml        19522 non-null  float64
 5   price_per_liter  19522 non-null  float64
 6   group            19522 non-null  object
 7   type             11725 non-null  object
 8   style            3961 non-null   object
 9   country          19522 non-null  object
 10  bitterness       2788 non-null   float64
 11  fullness         5292 non-null   float64
 12  sweetness        4249 non-null   float64
dtypes: float64(7), int64(1), object(5)
memory usage: 1.9+ MB

In [4]:
ratebeer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110364 entries, 0 to 110363
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   beer_id          110364 non-null  int64
 1   beer_name        110364 non-null  object
 2   n_reviews        110364 non-null  int64
 3   brewer_id        110364 non-null  int64
 4   beer_abv         87244 non-null   float64
 5   beer_style       110364 non-null  object
 6   appearance_mean  110364 non-null  float64
 7   appearance_std   85798 non-null   float64
 8   aroma_mean       110364 non-null  float64
 9   aroma_std        85798 non-null   float64
 10  palate_mean      110364 non-null  float64
 11  palate_std       85798 non-null   float64
 12  taste_mean       110364 non-null  float64
 13  taste_std        85798 non-null   float64
 14  overall_mean     110364 non-null  float64
 15  overall_std      85798 non-null   float64
dtypes: float64(11), int64(3), object(2)
memory usage: 13.5+ MB

In [5]:
beeradv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44083 entries, 0 to 44082
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   beer_id          44083 non-null  int64
 1   beer_name        44083 non-null  object
 2   n_reviews        44083 non-null  int64
 3   beer_abv         44083 non-null  float64
 4   beer_style       44083 non-null  object
 5   appearance_mean  44083 non-null  float64
 6   appearance_std   30341 non-null  float64
 7   palate_mean      44083 non-null  float64
 8   palate_std       30341 non-null  float64
 9   taste_mean       44083 non-null  float64
 10  taste_std        30341 non-null  float64
 11  overall_mean     44083 non-null  float64
 12  overall_std      30341 non-null  float64
dtypes: float64(9), int64(2), object(2)
memory usage: 4.4+ MB

In [6]:
# Keep only beers from sysbo.
mask = sysbo_df['group'] == 'Beer'
sysbo_df = sysbo_df[mask]
sysbo_df.head()

,number,name,abv,price,volume_ml,price_per_liter,group,type,style,country,bitterness,fullness,sweetness
3,8936603,Midas Golden Pilsner,4.9,27.9,330.0,84.55,Beer,Ljus lager,Pilsner - tjeckisk stil,Sverige,6.0,6.0,1.0
6,8983803,Schlappeseppel Specialität,5.6,29.9,330.0,90.61,Beer,Mellanmörk lager,Märzen och wienerstil,Tyskland,NaN,NaN,NaN
7,8996703,Schlappeseppel Dunkel,5.2,22.8,330.0,69.09,Beer,Mörk lager,Dunkel,Tyskland,NaN,NaN,NaN
8,8998601,Schlappeseppel Hefe Weissbier,5.5,28.7,500.0,57.40,Beer,Veteöl,Hefeweizen,Tyskland,NaN,NaN,NaN
9,8993603,Schlappeseppel Pils,5.1,22.8,330.0,69.09,Beer,Ljus lager,Pilsner - tysk stil,Tyskland,NaN,NaN,NaN

In [7]:
mask = sysbo_df['group']
mergedStuff = sysbo_df.merge(beeradv_df, left_on=['abv'], right_on=['beer_abv'], how='inner')

In [8]:
mergedStuff.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4938740 entries, 0 to 4938739
Data columns (total 26 columns):
 #   Column           Dtype
---  ------           -----
 0   number           int64
 1   name             object
 2   abv              float64
 3   price            float64
 4   volume_ml        float64
 5   price_per_liter  float64
 6   group            object
 7   type             object
 8   style            object
 9   country          object
 10  bitterness       float64
 11  fullness         float64
 12  sweetness        float64
 13  beer_id          int64
 14  beer_name        object
 15  n_reviews        int64
 16  beer_abv         float64
 17  beer_style       object
 18  appearance_mean  float64
 19  appearance_std   float64
 20  palate_mean      float64
 21  palate_std       float64
 22  taste_mean       float64
 23  taste_std        float64
 24  overall_mean     float64
 25  overall_std      float64
dtypes: float64(16), int64(3), object(7)
memory usage: 1017.3+ MB

In [12]:
from textdistance import levenshtein
from time import time

start = time()
print(mergedStuff.shape)

mini = mergedStuff[:100000]

mini['lev'] = mini.apply(lambda x: levenshtein.distance(x['name'],  x['beer_name']), axis=1)
print(time()-start)

(4938740, 26)
114.3365581035614

c:\users\pinaa\documents\git-repo\tvtime-dataviz\jupy_venv\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [13]:
mini[['number', 'name', 'group', 'abv', 'beer_name', 'beer_id', 'lev']].sort_values(by='lev', ascending=True)[:40]

,number,name,group,abv,beer_name,beer_id,lev
36390,145414,Pistonhead Kustom Lager,Beer,4.9,Pistonhead Kustom Lager,73876,0
4974,8913906,Pistonhead Kustom Lager,Beer,4.9,Pistonhead Kustom Lager,73876,1
6038,8120603,Trumer Pils,Beer,4.9,Ritter Pils,34486,4
6021,8120603,Trumer Pils,Beer,4.9,Hummel Pils,32803,4
6084,8120603,Trumer Pils,Beer,4.9,Lohrer Pils,38456,4
6158,8120603,Trumer Pils,Beer,4.9,Keller Pils,45603,4
6032,8120603,Trumer Pils,Beer,4.9,Keller-Pils,33808,5
9328,8923201,Leikeim Premium Pils,Beer,4.9,Leikeim Premium,6396,5
5819,8120603,Trumer Pils,Beer,4.9,Meister Pils,11305,5
99828,3146414,UP[P],Beer,5.6,HPA,75461,5
88585,3475415,Red Fox,Beer,5.6,Redd,54928,5
6289,8120603,Trumer Pils,Beer,4.9,Trukker Ur-Pils,61988,5
27735,3127115,Bellona,Beer,4.9,Merlyn,65306,5
62595,3346103,Motala Pils,Beer,5.6,Ivona Pils,23221,5
5918,8120603,Trumer Pils,Beer,4.9,Maisel Pils,21610,5
32660,8854203,Quilmes,Beer,4.9,Pilserl,56913,5
5978,8120603,Trumer Pils,Beer,4.9,Beckers Pils,26546,5
6088,8120603,Trumer Pils,Beer,4.9,Premium Pils,38596,5
27801,3127115,Bellona,Beer,4.9,Bulldog,71529,5
62108,8031903,Supporter,Beer,5.6,WB Porter,19392,5
44422,3037603,Nääs Pale Ale,Beer,4.9,Feral Pale Ale,16187,6
9787,8923201,Leikeim Premium Pils,Beer,4.9,Gessner Premium Pils,54637,6
99384,3146414,UP[P],Beer,5.6,Weizen,1819,6
61352,3334403,Caliban,Beer,5.6,Sorbon X,49587,6
27520,3127115,Bellona,Beer,4.9,Speltor,40007,6
99670,3146414,UP[P],Beer,5.6,Isis,57221,6
32825,8854203,Quilmes,Beer,4.9,Able,74705,6
35000,151612,König Pilsener,Beer,4.9,Gilde Pilsener,3326,6
61121,3334403,Caliban,Beer,5.6,Weizen,1819,6
5932,8120603,Trumer Pils,Beer,4.9,Roger's Pils,22799,6
61177,3334403,Caliban,Beer,5.6,CarnivAle,16131,6
5954,8120603,Trumer Pils,Beer,4.9,Diebels Pils,24143,6
27599,3127115,Bellona,Beer,4.9,Iguana,48380,6
27642,3127115,Bellona,Beer,4.9,Brusca,54937,6
32650,8854203,Quilmes,Beer,4.9,Vai Zen,56183,6
61155,3334403,Caliban,Beer,5.6,Carls Dark,11194,6
32270,8854203,Quilmes,Beer,4.9,Piss,14609,6
8582,150603,Jever Pilsener,Beer,4.9,Gilde Pilsener,3326,6
72446,3423315,Diamante,Beer,5.6,Gangster,54600,6
27683,3127115,Bellona,Beer,4.9,Beatrice,58670,6

In [53]:
mask = sysbo_df['name'].value_counts() >= 2
mask.sum()

3723

In [67]:
mask = beeradv_df['beer_name'].value_counts()
mask[mask > 1].sum()

11903

In [58]:
beeradv_df.shape

(66055, 13)